{
 "title": "Dashboard station temp réel tempo",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dept",
    "query": "SELECT DISTINCT DepartmentNum AS __value, DepartmentNum AS __text\nFROM ShopActivityHistorical\nWHERE DepartmentNum IS NOT NULL\nORDER BY DepartmentNum;"
   },
   {
    "name": "wc",
    "query": "SELECT DISTINCT WorkCenterNum AS __value, WorkCenterNum AS __text\nFROM ShopActivityHistorical\nWHERE DepartmentNum = '${dept}'\n  AND WorkCenterNum IS NOT NULL\nORDER BY WorkCenterNum;"
   },
   {
    "name": "of",
    "query": "SELECT DISTINCT\n  p.of_num AS __value,\n  p.of_num AS __text\nFROM (\n  SELECT REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') AS of_num\n  FROM kpi_db.planning_mlg_grafana v\n  WHERE v.`${Operation:raw}` IS NOT NULL\n\n  UNION\n\n  SELECT REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') AS of_num\n  FROM kpi_db.planning_nlg_grafana v\n  WHERE v.`${Operation:raw}` IS NOT NULL\n) p\nWHERE p.of_num <> ''\nORDER BY p.of_num;"
   },
   {
    "name": "Operation",
    "label": "Operation",
    "query": "SELECT REPLACE('${Operation}', 'Op ', '') AS __value;"
   }
  ]
 },
 "panels": [
  {
   "title": "Departement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT '${dept}' AS Departement;"
    }
   ]
  },
  {
   "title": "Station",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "kpi_db", "rawSql": "SELECT '${wc}' AS WorkCenter;" }
   ]
  },
  {
   "title": "Numéro d'OF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "kpi_db", "rawSql": "SELECT '${of}' AS OF_Num;" }
   ]
  },
  {
   "title": "Numéro d'opération",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT '${Operation}' AS Numero_operation;"
    }
   ]
  },
  {
   "title": "Retard temps de travail effectifs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "New panel",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  DATE_FORMAT(MIN(start_dt), '%d/%m %H:%i') AS real_start_short,\r\n\r\n  ROUND(SUM(worked_h), 2)  AS worked_h,\r\n  ROUND(SUM(planned_h), 2) AS planned_h,\r\n\r\n  DATE_FORMAT(\r\n    DATE_ADD(MIN(start_dt), INTERVAL ROUND(SUM(planned_h) * 3600) SECOND),\r\n    '%d/%m %H:%i'\r\n  ) AS theo_end_short,\r\n\r\n  ROUND(GREATEST(SUM(planned_h) - SUM(worked_h), 0), 2) AS remaining_h,\r\n\r\n  ROUND(GREATEST(\r\n    TIMESTAMPDIFF(\r\n      SECOND,\r\n      DATE_ADD(MIN(start_dt), INTERVAL ROUND(SUM(planned_h) * 3600) SECOND),\r\n      NOW()\r\n    ) / 3600, 0\r\n  ), 2) AS delay_pos_h,\r\n\r\n  -- jauge Canvas en %\r\n  LEAST(\r\n    ROUND(\r\n      100 * IFNULL(SUM(worked_h) / NULLIF(SUM(planned_h), 0), 0),\r\n      1\r\n    ),\r\n    200\r\n  ) AS pct_100\r\n\r\nFROM (\r\n  SELECT\r\n    OperationDescription,\r\n    MIN(STR_TO_DATE(AdjustedStartTime, '%Y-%m-%d %H:%i:%s.%f')) AS start_dt,\r\n    SUM(COALESCE(TotalLaborRunHours_Actual, 0)) AS worked_h,\r\n    MAX(COALESCE(PlannedRunHours, 0)) AS planned_h\r\n  FROM ShopActivityHistorical\r\n  WHERE DepartmentNum = '${dept}'\r\n    AND WorkCenterNum = '${wc}'\r\n    AND OrderNum = '${of}'\r\n    AND AdjustedStartTime IS NOT NULL\r\n  GROUP BY OperationDescription\r\n) t;"
    }
   ]
  },
  {
   "title": "Jauge temps de travail",
   "type": "gauge",
   "description": "Vert < 90% du prévu • Orange 90–100% • Rouge > 100%",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h  " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(SUM(t.worked_h), 2)  AS worked_h,\r\n  ROUND(SUM(t.planned_h), 2) AS planned_h,\r\n\r\n  /* max de gauge = planned (fixe) */\r\n  ROUND(SUM(t.planned_h), 2) AS gauge_max_h,\r\n\r\n  /* seuils dynamiques basés sur planned */\r\n  ROUND(SUM(t.planned_h) * 0.90, 2) AS thr_orange,\r\n  ROUND(SUM(t.planned_h) * 1.00, 2) AS thr_red,\r\n\r\n  /* infos complémentaires */\r\n  ROUND(GREATEST(SUM(t.planned_h) - SUM(t.worked_h), 0), 2) AS remaining_h,\r\n  ROUND(GREATEST(SUM(t.worked_h) - SUM(t.planned_h), 0), 2) AS delay_h,\r\n  ROUND(SUM(t.worked_h) - SUM(t.planned_h), 2) AS delta_h\r\n\r\nFROM (\r\n  SELECT\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription,\r\n\r\n    SUM(COALESCE(s.TotalLaborRunHours_Actual, 0)) AS worked_h,\r\n    MAX(COALESCE(s.PlannedRunHours, 0))           AS planned_h\r\n\r\n  FROM ShopActivityHistorical s\r\n  WHERE s.DepartmentNum = '${dept}'\r\n    AND s.WorkCenterNum = '${wc}'\r\n    AND s.OrderNum = '${of}'\r\n   \r\n  GROUP BY\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription\r\n) t;"
    }
   ]
  },
  {
   "title": "Temps restant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(SUM(t.worked_h), 2) AS worked_h,\r\n  ROUND(SUM(t.planned_h), 2) AS planned_h,\r\n\r\n  /* max de gauge = planned (fixe) */\r\n  ROUND(SUM(t.planned_h), 2) AS gauge_max_h,\r\n\r\n  /* seuils dynamiques basés sur planned */\r\n  ROUND(SUM(t.planned_h) * 0.90, 2) AS thr_orange,\r\n  ROUND(SUM(t.planned_h), 2) AS thr_red,\r\n\r\n  /* infos complémentaires */\r\n  ROUND(GREATEST(SUM(t.planned_h) - SUM(t.worked_h), 0), 2) AS remaining_h,\r\n  ROUND(GREATEST(SUM(t.worked_h) - SUM(t.planned_h), 0), 2) AS delay_h,\r\n  ROUND(SUM(t.worked_h) - SUM(t.planned_h), 2) AS delta_h\r\nFROM (\r\n  SELECT\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription,\r\n    SUM(COALESCE(s.TotalLaborRunHours_Actual, 0)) AS worked_h,\r\n    MAX(COALESCE(s.PlannedRunHours, 0)) AS planned_h\r\n  FROM ShopActivityHistorical s\r\n  WHERE s.DepartmentNum = '${dept}'\r\n    AND s.WorkCenterNum = '${wc}'\r\n    AND s.OrderNum = '${of}'\r\n  GROUP BY\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription\r\n) t;"
    }
   ]
  },
  {
   "title": "Retard ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(SUM(t.worked_h), 2) AS worked_h,\r\n  ROUND(SUM(t.planned_h), 2) AS planned_h,\r\n\r\n  /* max de gauge = planned (fixe) */\r\n  ROUND(SUM(t.planned_h), 2) AS gauge_max_h,\r\n\r\n  /* seuils dynamiques basés sur planned */\r\n  ROUND(SUM(t.planned_h) * 0.90, 2) AS thr_orange,\r\n  ROUND(SUM(t.planned_h), 2) AS thr_red,\r\n\r\n  /* infos complémentaires */\r\n  ROUND(GREATEST(SUM(t.planned_h) - SUM(t.worked_h), 0), 2) AS remaining_h,\r\n  ROUND(GREATEST(SUM(t.worked_h) - SUM(t.planned_h), 0), 2) AS delay_h,\r\n  ROUND(SUM(t.worked_h) - SUM(t.planned_h), 2) AS delta_h\r\nFROM (\r\n  SELECT\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription,\r\n    SUM(COALESCE(s.TotalLaborRunHours_Actual, 0)) AS worked_h,\r\n    MAX(COALESCE(s.PlannedRunHours, 0)) AS planned_h\r\n  FROM ShopActivityHistorical s\r\n  WHERE s.DepartmentNum = '${dept}'\r\n    AND s.WorkCenterNum = '${wc}'\r\n    AND s.OrderNum = '${of}'\r\n  GROUP BY\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription\r\n) t;"
    }
   ]
  },
  {
   "title": "Temps prévu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(SUM(t.worked_h), 2) AS worked_h,\r\n  ROUND(SUM(t.planned_h), 2) AS planned_h,\r\n\r\n  /* max de gauge = planned (fixe) */\r\n  ROUND(SUM(t.planned_h), 2) AS gauge_max_h,\r\n\r\n  /* seuils dynamiques basés sur planned */\r\n  ROUND(SUM(t.planned_h) * 0.90, 2) AS thr_orange,\r\n  ROUND(SUM(t.planned_h), 2) AS thr_red,\r\n\r\n  /* infos complémentaires */\r\n  ROUND(GREATEST(SUM(t.planned_h) - SUM(t.worked_h), 0), 2) AS remaining_h,\r\n  ROUND(GREATEST(SUM(t.worked_h) - SUM(t.planned_h), 0), 2) AS delay_h,\r\n  ROUND(SUM(t.worked_h) - SUM(t.planned_h), 2) AS delta_h\r\nFROM (\r\n  SELECT\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription,\r\n    SUM(COALESCE(s.TotalLaborRunHours_Actual, 0)) AS worked_h,\r\n    MAX(COALESCE(s.PlannedRunHours, 0)) AS planned_h\r\n  FROM ShopActivityHistorical s\r\n  WHERE s.DepartmentNum = '${dept}'\r\n    AND s.WorkCenterNum = '${wc}'\r\n    AND s.OrderNum = '${of}'\r\n  GROUP BY\r\n    s.DepartmentNum,\r\n    s.WorkCenterNum,\r\n    s.OrderNum,\r\n    s.OperationDescription\r\n) t;"
    }
   ]
  },
  {
   "title": "Vision par rapport au Takt Théorique",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  /* Début théorique (planning) */\r\n  DATE_FORMAT(MIN(t.takt_start_dt), '%d/%m %H:%i') AS takt_start_short,\r\n\r\n  /* Fin théorique (planning) */\r\n  DATE_FORMAT(MAX(t.takt_end_dt), '%d/%m %H:%i')   AS takt_end_short,\r\n\r\n  /* Début réel (runtime) */\r\n  DATE_FORMAT(MIN(t.real_start_dt), '%d/%m %H:%i') AS real_start_short\r\n\r\nFROM (\r\n  /* planning MLG */\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i') AS takt_start_dt,\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i') AS takt_end_dt,\r\n    NULL AS real_start_dt\r\n  FROM kpi_db.planning_mlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n\r\n  UNION ALL\r\n\r\n  /* planning NLG */\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i'),\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i'),\r\n    NULL\r\n  FROM kpi_db.planning_nlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n\r\n  UNION ALL\r\n\r\n  /* début réel (ShopActivityHistorical) */\r\n  SELECT\r\n    NULL,\r\n    NULL,\r\n    MIN(STR_TO_DATE(s.AdjustedStartTime, '%Y-%m-%d %H:%i:%s.%f')) AS real_start_dt\r\n  FROM ShopActivityHistorical s\r\n  WHERE s.DepartmentNum='${dept}'\r\n    AND s.WorkCenterNum='${wc}'\r\n    AND s.OrderNum='${of}'\r\n   \r\n    AND s.AdjustedStartTime IS NOT NULL\r\n) t;"
    }
   ]
  },
  {
   "title": "Avancement par rapport au takt",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(GREATEST(TIMESTAMPDIFF(SECOND, MIN(start_dt), NOW()) / 3600, 0), 2) AS takt_elapsed_h,\r\n  ROUND(TIMESTAMPDIFF(SECOND, MIN(start_dt), MAX(end_dt)) / 3600, 2)       AS gauge_max_h,\r\n  ROUND((TIMESTAMPDIFF(SECOND, MIN(start_dt), MAX(end_dt)) / 3600) * 0.90, 2) AS thr_orange,\r\n  ROUND((TIMESTAMPDIFF(SECOND, MIN(start_dt), MAX(end_dt)) / 3600) * 1.00, 2) AS thr_red\r\nFROM (\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i') AS start_dt,\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i') AS end_dt\r\n  FROM kpi_db.planning_mlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n\r\n  UNION ALL\r\n\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i'),\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i')\r\n  FROM kpi_db.planning_nlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n) p;"
    }
   ]
  },
  {
   "title": "Retard ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(GREATEST(TIMESTAMPDIFF(SECOND, MAX(end_dt), NOW()) / 3600, 0), 2) AS takt_delay_h\r\nFROM (\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i') AS start_dt,\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i') AS end_dt\r\n  FROM kpi_db.planning_mlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n  UNION ALL\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i'),\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i')\r\n  FROM kpi_db.planning_nlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n) p;"
    }
   ]
  },
  {
   "title": "Temps restant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(GREATEST(TIMESTAMPDIFF(SECOND, NOW(), MAX(end_dt)) / 3600, 0), 2) AS takt_ahead_h\r\nFROM (\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i') AS start_dt,\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i') AS end_dt\r\n  FROM kpi_db.planning_mlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n  UNION ALL\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i'),\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i')\r\n  FROM kpi_db.planning_nlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n) p;"
    }
   ]
  },
  {
   "title": "Temps prévu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kpi_db",
     "rawSql": "SELECT\r\n  ROUND(TIMESTAMPDIFF(SECOND, MIN(start_dt), MAX(end_dt)) / 3600, 2) AS takt_planned_h\r\nFROM (\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i') AS start_dt,\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i') AS end_dt\r\n  FROM kpi_db.planning_mlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n  UNION ALL\r\n  SELECT\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Début`), '%Y %d/%m %H:%i'),\r\n    STR_TO_DATE(CONCAT(YEAR(CURDATE()), ' ', v.`Heure Fin`),   '%Y %d/%m %H:%i')\r\n  FROM kpi_db.planning_nlg_grafana v\r\n  WHERE REPLACE(TRIM(CAST(v.`${Operation:raw}` AS CHAR)), '.0', '') = REPLACE('${of}', '.0', '')\r\n) p;"
    }
   ]
  }
 ]
}